# latexmk configuration for this paper (uplatex + dvipdfmx)

$latex = 'uplatex %O -synctex=1 -interaction=nonstopmode -file-line-error %S';
$bibtex = 'upbibtex %O %B';
$dvipdf = 'dvipdfmx %O -o %D %S';

# 3: generate pdf via dvi -> dvipdf
$pdf_mode = 3;
